@extends('layouts.3dRPC')



@section('head') @parent
 <link rel="stylesheet" type="text/css" href="/css/introjs.min.css" media="all" />
@endsection

@section('content-main')
    <div class='panel panel-default'>
        <div class='panel-heading' >
            <h3 class='panel-title'>New Task</h3>
        </div>
        <div class='panel-body'>
            <form v-el:form class='form-horizontal' method="POST" name='form1' enctype="multipart/form-data" onsubmit="return false;" >
                <!-- <input type="hidden" name="_token" v-model="token"> -->
                <div class='form-group' data-step="1" data-intro="(Optional) Input your email.">
                    <label class="col-sm-2 control-label">Email (optional)</label>
                        <div class="col-sm-4">
                            <input type="text"  name="email" class='form-control' v-model="email" :placeholder="email_prompt" :title="email_prompt">
                        </div>
                </div>


                <div class='form-group' data-step="2" data-intro="Upload your protein structure in PDB format">
                    <label class="col-sm-2 control-label">Protein structure</label>
                    <div class='col-sm-4'>
                        <input v-el:file type="file" name="protein" />
                    </div>
                    <div class='col-sm-4'>
                        <a href="/download/1DFU_r_u.pdb">Example of protein structure file</a>      
                    </div>
                </div>
  


                <div class='form-group' data-step="3" data-intro="Upload your RNA structure in PDB format">
                    <label class="col-sm-2 control-label">RNA structure</label>
                    <div class='col-sm-4'>
                        <input v-el:file type="file" name="rna" />
                    </div>
                     <div class='col-sm-4'>
                        <a href="/download/1DFU_l_u.pdb">Example of RNA structure file</a>
                    </div>

                </div>

                <div class='form-group' data-step="4" data-intro="Number of complexes generated by 3dRPC">
                    <label class="col-sm-2 control-label">Number of predictions</label>
                        <div class="col-sm-4">
                            <input type="text" value="10" name="num" class='form-control' v-model="num" :placeholder="num_prompt" :title="num_prompt">
                        </div>
                </div>

                <div class='form-group' data-step="5" data-intro="choosing scoring functions">
                    <label class="col-sm-2 control-label">Scoring functions</label>
                        <div class="col-sm-4">
                            <select name="sf" class='form-control' v-model="sf" :placeholder="sf_prompt" :title="sf_prompt">
                            <option selected>RPRANK</option>
                            <option>DECK-RP</option>
                            </select>
                        </div>
                </div>


                <div class='form-group'>
                    <div class='col-sm-offset-3 col-sm-3'>
                     <button class="btn btn-info" @click="submit" data-step="6" data-intro="Submit the task." :disabled="disable_submit_button || show_success" v-text="text_submit_button">Submit</button>
                        <button type='reset' class='btn btn-warning'>Clear</button>
                    </div>
                </div>

            </form>

            <div class='row'>
                    <small class='col-sm-offset-2 col-sm-12'>
                    <em>Get help from the <a href="#" v-on:click="show_guide" >step-by-step guid</a></em> or the 
                    <a href="/download/3dRPC-um.pdf">documentation</a> of 3dRPC
                    </small>
            </div>

<vue-alert type="success" :show="show_success" :contents="success"></vue-alert>

<vue-alert type="danger" :show="show_errors" :contents="errors"></vue-alert>
        </div>
    </div>
    
    <div class='panel panel-default' v-if="running_tasks.length">
        <div class='panel-heading'>
            <h3 class='panel-title'>Submitted Tasks <a @click="get_running_tasks" title="Refresh"><span class="glyphicon glyphicon-refresh @{{rotate_refresh}}"></span></a></h3>
        </div>
        <div class='panel-body'>
            <vue-tasks :tasks="running_tasks" :page=1 :page_size=10 :items="{id:'num',submit_at:'submit_time'}" task_type="3dRPC/result"></vue-tasks>
        </div>
    </div>


    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Query Task</h3>
                </div>
                <div class="panel-body">
                <vue-query></vue-query>
                <vue-alert type="danger" :show="show_query_errors" :contents="query_errors"></vue-alert>
                    <template v-if="query_results.length != 0">
                        <vue-tasks :tasks="query_results" :page=1 :page_size=10 :items="{id:'num',submit_at:'submit_time'}" task_type="3dRPC/result"></vue-tasks>
                    </template>
        </div>
   </div>

    <!-- picture -->

    <div class='panel panel-default'>
        <div class='panel-body'>
            <div class='row'>
                <div class='col-sm-6'>
                    <div class="thumbnail">
                        <img class='img-responsive' src="/images/2ZM5.png" />
                    </div>
                    <p>(A)An example of complex successfully predicted by 3dRPC. The dark color
represents native structures and the light color represents predicted one. Proteins of predicted structures are superimposed onto native structures. </p>
                </div>
                <div class='col-sm-6'>
                    <div class="thumbnail">
                        <img class='img-responsive' src="/image/3drpc-fig1.jpg" />
                    </div>
                    <p>(B) Success rate of RPRANK/3dRPC-Score on test set.</p>
                </div>
            </div>
        </div>
    </div>


    <!-- References -->
    <div class='panel panel-default'>
        <div class='panel-body'>
            References:
            <br />
            <ol>
                <li>
                    Huang, Y., et al.,
                    <a href="http://biophy.hust.edu.cn/download/3dRPC.pdf">
                                    a novel protocol for three-dimensional structure prediction of RNA-protein complexes
                                                        </a>.
                                                                            Scientific Reports, 2013. 3: p. 1887.

                </li>
            </ol>
        </div>
    </div>
@endsection

@section('main-js')
    <script type="text/javascript" src="/js/intro.min.js"></script>
    <script type="text/javascript" src="/js/vue.min.js"></script>
    <script type="text/javascript" src="/js/vue-resource.min.js"></script>
    <script type="text/javascript" src="/js/vue-alert.js"></script>
    <script type="text/javascript">
        var browser = {
            versions: function() {
                var u = navigator.userAgent, app = navigator.appVersion;
                return {//移动终端浏览器版本信息
                    trident: u.indexOf('Trident') > -1, //IE内核
                    presto: u.indexOf('Presto') > -1, //opera内核
                    webKit: u.indexOf('AppleWebKit') > -1, //苹果、谷歌内核
                    gecko: u.indexOf('Gecko') > -1 && u.indexOf('KHTML') == -1, //火狐内核
                    mobile: !!u.match(/AppleWebKit.*Mobile.*/) || !!u.match(/AppleWebKit/), //是否为移动终端
                    ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), //ios终端
                    android: u.indexOf('Android') > -1 || u.indexOf('Linux') > -1, //android终端或者uc浏览器
                    iPhone: u.indexOf('iPhone') > -1 || u.indexOf('Mac') > -1, //是否为iPhone或者QQHD浏览器
                    iPad: u.indexOf('iPad') > -1, //是否iPad
                    webApp: u.indexOf('Safari') == -1 //是否web应该程序，没有头部与底部
                };
            }(),
            language: (navigator.browserLanguage || navigator.language).toLowerCase()
        }

        Vue.http.options.emulateJSON = true;
        var v = new Vue({
            el: "#vue-main",
           // data: merge_objects(state, info),
            
            data: {
                email: "",
                errors: [],
                query_results: [],
                query_errors: "",    
                show_query_errors: false,
                show_errors: false,
                show_results: false,
                show_success: false,
                results: '',
                ip: "{{$ip}}",
                running_tasks: [],
                success: [],
                disable_submit_button: false,
                text_submit_button: "Submit", submit_disabled: false,
            },


            methods: {
                submit: function(){
                
                    var v = this;
                    v.disable_submit_button = true
                    v.text_submit_button = "submitting..."
                    jian_ajax("POST","http://biophy.hust.edu.cn/3dRPC/submit", new FormData(v.$els.form),function(response) {
                    console.log(response)
                    var task_id = JSON.parse(response).task_id
                    v.success = ["Your task has been submitted successfully!<br>"+
                    "You can visit <a target='_blank' href='/3dRPC/result/"+task_id+
                    "'>http://biophy.hust.edu.cn/3dRPC/result/"+task_id+"</a> to follow up the progress of the task.<br>"+
                    "Refresh this page then you can submit a new task!"]

                    v.show_errors = false
                    v.show_success = true
                    v.disable_submit_button = true
                    v.text_submit_button = "Submit"
                    v.get_running_tasks()
                    },function(response){
                    console.log(response)
                    v.errors = JSON.parse(response).errors
                    v.disable_submit_button = false
                    v.text_submit_button = "Submit"
                    v.show_errors = true
                    v.show_success = false
                    })
                },


                get_running_tasks: function() {
                var v = this
                v.rotate_refresh = 'refresh'
                jian_ajax("GET", "http://biophy.hust.edu.cn/3dRPC/running_tasks/"+v.ip, function(response){
                    var r = JSON.parse(response)
                    r.sort(function(a, b){
                        return b.submit_time-a.submit_time
                    })
                    console.log(r)
                    v.running_tasks = r
                    v.rotate_refresh = ''
                    }, function(response){
                        console.log(response)
                        v.rotate_refresh = ''
                    })
                },

                show_guide: function(e) {
                    var v = this
                    introJs().oncomplete(function(){
                        v.disable_submit_button = false
                        v.email = ""
                        v.text_submit_button = "Submit"
                        v.show_success = false
                    }).onafterchange(function(e){
                        var intro = this
                        var n = parseInt(e.getAttribute("data-step"))
                        setTimeout(function(){
                            if(n==6) {
                            v.text_submit_button = "submitting..."
                            v.disable_submit_button = true
                            } else if(n==1) {
                            v.email = 'XXXXXX@163.com'  
                            } else if ( n==2) {
                            v.protein = 'protein.pdb'
                            }
                        },1000)
                        setTimeout(function(){intro.nextStep();}, 4000)
                    }).setOption("showButtons",false).setOption("exitOnOverlayClick",false).start()
                },
            },


            events: {
                "vue-query-submit": function(query, el) {
                var v = this
                jian_ajax("POST", "http://biophy.hust.edu.cn/3dRPC/query", new FormData(el), function(response){
                console.log(response)
                var r = JSON.parse(response).results
                r.sort(function(a, b){
                    return b.submit_time-a.submit_time
                })
                v.query_results = r
                v.show_query_errors = false
                }, function(response){
                    console.log(response)
                    v.query_results = []
                    v.query_errors = JSON.parse(response).errors
                    v.show_query_errors = true
                })
                },
            },
        })
        v.get_running_tasks()

    </script>

@endsection

